### ISSUE TITLE
7th edition link incorrect

### ISSUE THREAD

**Issue by eclectic-coding** [learnenough/sample_app_6th_ed#65]
FYI. The draft version of 7th edition Listing 3.47 links to the [Guardfile](https://github.com/mhartl/sample_app_6th_ed/blob/main/Guardfile) here, but the listings are different. 

Namely, the `require` statement. Just wanted to let you know. 

Thanks for the new release.

**Comment by mhartl** [comment]
Great catch! It’s now fixed. Thanks!
